spring:
  datasource:
    url: jdbc:mysql://localhost:3306/kohonen?useSSL=false
    username: webapp
    password: webpass
  jpa:
    generate-ddl: false
    show-sql: false
    hibernate:
      ddl-auto: validate
      naming:
        strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect

coeff:
  hsb: 1
  grad: 3
  ratio: 2
        
    